# Generated by Django 4.2.27 on 2026-01-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "alcohol_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("stock", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="product",
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
