# Generated by Django 4.2.27 on 2026-01-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitem_variant_cart_user_cartitem_cart"),
        ("products", "0002_variant_remove_productvariant_product_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductVariant",
        ),
        migrations.AddField(
            model_name="variant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
            ),
        ),
    ]
