# Generated by Django 4.2.27 on 2026-01-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_price",
            new_name="total_amount",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="variant_details",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant_info",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=150),
        ),
    ]
