# Generated by Django 4.2.27 on 2026-01-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="created_at",
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
